apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-todo-delete-tasks-api-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-todo-delete-tasks-api
  ports:
    - port: {{.Values.deleteTask.svcPort}}
      targetPort: {{.Values.deleteTask.containerPort}}
