apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-todo-add-tasks-api-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-todo-add-tasks-api
  ports:
    - port: {{.Values.addTask.svcPort}}
      targetPort: {{.Values.addTask.containerPort}}
