apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-get-task-api-ingress
spec:
  ingressClassName: {{.Values.common.ingressClassName}}
  rules:
  - host: {{.Release.Name}}.get-task-api.{{.Values.common.hostDomain}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{.Release.Name}}-todo-get-tasks-api-svc
            port: 
              number: {{.Values.getTask.svcPort}}
